use_frameworks!

platform :ios, '9.0'

target 'SMUtils_Example' do
  pod 'SMUtils', :path => '../'

  target 'SMUtils_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
